---

- hosts: all
  become: true
  vars:
    - gitlab_password: "{{ pb_root_password }}"
    - reboot_connect_timeout: 5
    - reboot_post_reboot_delay: 15
    - reboot_timeout: 600

  tasks:
    - name: Install EPEL package
      ignore_errors: yes
      become: true
      yum:
       state: present
       name:
         - yum-plugin-fastestmirror
         - epel-release
         - wget
         - unzip
         - curl
         - policycoreutils-python
         - openssh-server
         - postfix
         - python-pip
    
    - name: install pexpect module using pip
      pip:
        state: present
        name: pexpect
        
    - name: Install Gitlab and Reset the password for ROOT user
      become: yes
      args:
        warn: false
      shell: |
        curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
        hostname=`curl ifconfig.co`
        GITLAB_ROOT_PASSWORD="{{ gitlab_password }}" EXTERNAL_URL="http://$hostname" yum install -y gitlab-ce


